id: I8AF3AC3C
default_language: fr
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:30:37.101210
last_modified: 2023-01-04 11:30:37.101219
source_metadata:
  collections:
  - Chatral Rinpoche
  - Works of Tibetan Masters
bases:
  FD81:
    title: 'The Rishi''s Maledictory Incantation: An Invocation of Wisdom Mind and
      Sacred Pledges for Reversing the Disturbances and Agitations of Dark Times In
      the Form of an Aspiration Prayer'
    base_file: FD81.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
